theme: minima
title: Conjectures of Gapski
author: Kiran Pannserselvam
email: kiran.pselvam@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Data, Statistics, Learning and Optimization

# social links
twitter_username: xkpsd # DO NOT include the @ character, or else the build will fail!
github_username:  kiranpselvam # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
